name: "PLG Deploy"
description: "Build and deploy plg addon to workshop"

inputs:
    workshop-id:
        description: "Steam Workshop ID"
        required: true

runs:
    using: "composite"
    steps:
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"
            cache: "pip"

        - name: Install dependencies
          shell: bash
          run: |
            set -euo pipefail
            python -m pip install -U pip
            pip install -U --prefer-binary pylovegmod-sdk

        - name: Build from source
          shell: bash
          run: |
            set -euo pipefail
            plg-sdk build

        - name: Pack build artefact
          shell: bash
          run: |
            set -euo pipefail
            python build_gma.py

        - name: Build steamcmd artefact
          shell: bash
          run: |
            set -euo pipefail

            NAME=$(jq -r '.release.name // .head_commit.message // "Build"' "$GITHUB_EVENT_PATH")
            BODY=$(jq -r '.release.body // .head_commit.message // ""' "$GITHUB_EVENT_PATH")

            python build_workshop_vdf.py \
                --workshop-id "${{ inputs.workshop-id }}" \
                --name "$NAME" \
                --description "$BODY"

        - name: Cache steamcmd
          uses: actions/cache@v4
          with:
            path: steamcmd
            key: steamcmd-linux-v1

        - name: Install steamcmd if missing
          shell: bash
          run: |
            set -euo pipefail

            if [ ! -f steamcmd/steamcmd.sh ]; then
                mkdir -p steamcmd
                cd steamcmd
                curl -sL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz \
                | tar -xz
            fi

        - name: Upload
          shell: bash
          env:
            STEAM_USER: ${{ secrets.STEAM_USER }}
            STEAM_PASS: ${{ secrets.STEAM_PASS }}
          run: |
            set -euo pipefail

            export LC_ALL=C

            cd steamcmd

            ./steamcmd.sh \
                +login "$STEAM_USER" "$STEAM_PASS" \
                +run_app_build ../workshop.vdf \
                +quit
